spring.application.name=soporte

spring.datasource.url=jdbc:mysql://mysql-graphixstory-duocuc-d2a7.h.aivencloud.com:23330/defaultdb?sslMode=REQUIRED&serverTimezone=UTC
##spring.datasource.url=${DB_URL}
spring.datasource.username=avnadmin
##spring.datasource.username=${USER_NAME}
spring.datasource.password=AVNS_yu0F1SIHxKFobZy1qCZ
##spring.datasource.password=${PASS_DB}

usuarios.api.url=http://localhost:8080/api/
##usuarios.api.url=${USUARIOS_API_URL}

server.port=${PORT:8080}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect